Improve hello_world/check output

diff --git a/hello_world/check b/hello_world/check
--- a/hello_world/check
+++ b/hello_world/check
@@ -1,5 +1,6 @@
 #!/bin/bash
-set -x
+#set -x
 export PATH=.:$PATH
 out=$($*)
-[ "$out" = "Hello, world" ] || exit 1
+[ "$out" = "Hello, world" ] || { printf "Failure\nExpected: Hello, world\nGot     : %s\n" "$out"; exit 1; }
+printf "Success!\n"
